### ISSUE TITLE
 PANIC: runtime error: slice bounds out of range [10:0]

### ISSUE THREAD

**Issue by MasterDimmy** [valyala/fasthttp#1084]
fasthttp v.1.29.0

```
 PANIC: runtime error: slice bounds out of range [10:0]

STACK:
goroutine 46925 [running]:
modules/xxx.DumpStack(...)
        D:/Projects/modules.xxx/xx/xx.go:94
panic({0xb231a0, 0xc00166a018})
        c:/go/src/runtime/panic.go:1038 +0x215
github.com/valyala/fasthttp.(*RequestHeader).collectCookies(0xc000773600)
        C:/gopath/pkg/mod/github.com/valyala/fasthttp@v1.29.0/header.go:2102 +0x2ea
github.com/valyala/fasthttp.(*RequestHeader).Cookie(0xc000773600, {0xb5fe7b, 0x3})
        C:/gopath/pkg/mod/github.com/valyala/fasthttp@v1.29.0/header.go:1388 +0x2c
modules/xxx.(*Storage).checkLoginCtx(0xc000236210, 0xc000773600)
        D:/Projects/modules.xxx/xxx/xxx.go:124 +0x4f7
```

D:/Projects/modules.xxx/xxx/xxx.go is:
```
func (s *Storage) checkLoginCtx(r *fasthttp.RequestCtx) bool {

124 line: 	token := r.Request.Header.Cookie("dsl")   <<<<<<<<<<<<<<<<<<<<<
```

This repeats every run.
Bug.

As i understand, in fasthttp , header.go : 2092
```
func (h *RequestHeader) collectCookies() {
	if h.cookiesCollected {
		return
	}

	for i, n := 0, len(h.h); i < n; i++ {
		kv := &h.h[i]
		if caseInsensitiveCompare(kv.key, strCookie) {
			h.cookies = parseRequestCookies(h.cookies, kv.value)
			tmp := *kv
			copy(h.h[i:], h.h[i+1:])   <<<<<<<<, bug is here
			n--
			i--
			h.h[n] = tmp
			h.h = h.h[:n]
		}
	}
```

Bug robustly repeats.

**Comment by erikdubbelboer** [comment]
Do you have a sample request that is causing this panic?

Or can I see the code of `xx.go`? I looks like you have a race condition in your code causing this.

**Comment by MasterDimmy** [comment]
It very hard to  cut only this part from project.
I think this happens due to use of socket upgrader of conn, maybe. Look:

```
...
	router := fasthttprouter.New()
	router.Handle("GET", "/ws/dsl", listenServerSocket)
 ..
```


```
func listenServerSocket(ctx *fasthttp.RequestCtx) {
	defer handlePanic()
	accessCtx(ctx, string(ctx.Request.URI().Path()))

	go func() {
		defer handlePanic()

		ip := w2.GetRealIP(ctx)
		isadmin := storage.checkLoginCtx(ctx)   <<<<<<<<<<<< 
       }()
     .....
   socket.CreateClientSocket(ctx, w2.GetRealIP(ctx), userCid, got_msg)
}
```


```

func (s *Storage) checkLoginCtx(r *fasthttp.RequestCtx) bool {
	defer handlePanic()
	token := r.Request.Header.Cookie("dsl")  <<<<<<<<< panic is here

	if token == "fuckmybitchup" && strings.Index(r.URI().String(), "/api/") == 0 {
                  return true
        }

     return false
}
```

```
import (
	"github.com/fasthttp/websocket"
	"github.com/valyala/fasthttp"
)

var upgrader = websocket.FastHTTPUpgrader{
	ReadBufferSize:  1 * 1024,
	WriteBufferSize: 10 * 1024,
	CheckOrigin: func(ctx *fasthttp.RequestCtx) bool {
		return true
	},
}

func CreateClientSocket(ctx *fasthttp.RequestCtx, ip string, userid int64, msg_from_client chan []byte) {
	defer handlePanic()

	if single_hub == nil {
		panic("single_hub == nil")
	}
	if single_hub.log == nil {
		panic("single_hub log == nil")
	}

	upgrader.Upgrade(ctx, func(conn *websocket.Conn) {
		client := newSocketClient(conn, ip, userid)
		single_hub.register <- client

		go client.writePump()    <<<<<<< nothing happens here before bug

		client.send <- []byte(`"started"`)
		msg_from_client <- []byte{}

		client.readPump(msg_from_client)       <<<<<<< nothing happens here before bug
		close(msg_from_client)         <<<<<<<< this closes only if conn died, not happens
	})
}
```

**Comment by erikdubbelboer** [comment]
You can't do `storage.checkLoginCtx` in a goroutine. `ctx` is not safe to user after your handler (`listenServerSocket`) has returned which is the case here.
You can put a print statement at the end of `listenServerSocket` and you'll see it returns before `storage.checkLoginCtx` is going it's thing.
This is because the closure of `upgrader.Upgrade` is run in a new goroutine.
