### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Zorkai** [valyala/fasthttp#1157]
Hello, I'm getting this error :
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x752678]

goroutine 15844 [running]:
github.com/valyala/fasthttp.(*Response).Body(0xc000104400)
        github.com/valyala/fasthttp@v1.29.0/http.go:325 +0x18
main.lKyiTcYc({0x9ec3f8, 0xc0001c84b0}, 0xc001e608c0)
        LQTQKubz.go:1 +0x87e
main.mL77Jmdk.func5()
        rhs3Hkn8.go:1 +0x45
created by main.mL77Jmdk
        GAGppx8W.go:3 +0x37f
```

Code :
```go
client := &fasthttp.Client{
	Dial: fasthttpproxy.FasthttpHTTPDialer(config.Proxies[0]),
}
strRequestURI := "https://discord.com/api/v9/invites/lol"
req := fasthttp.AcquireRequest()
req.Header.SetMethod("GET")
req.SetRequestURI(strRequestURI)
res := fasthttp.AcquireResponse()

if err := client.Do(req, res); err != nil {
	logWithTime(err.Error())
	return
}

fasthttp.ReleaseRequest(req)
body := string(res.Body())
fasthttp.ReleaseResponse(res)
```

**Comment by erikdubbelboer** [comment]
Can you please share your whole code cause I'm sure that is not it. If you look at [http.go:325](https://github.com/valyala/fasthttp/blob/v1.29.0/http.go#L325) you can see this happens when you call `Response.Body()` on a `nil` response. This is not possible in the code you posted. Your stack trace also doesn't make any sense with everything being on line 1.
