### ISSUE TITLE
is it possible fasthttp rise evict panic?

### ISSUE THREAD

**Issue by ben-swit** [valyala/fasthttp#1368]
like that issue comment https://github.com/grpc/grpc-go/issues/4412#issuecomment-838075237

has to do with fasthttp??

**Comment by erikdubbelboer** [comment]
No, that whole issue has nothing to do with fasthttp. I have no idea why @Chinaren-Wei commented that.

**Comment by ben-swit** [comment]
but i have same issue 

```
panic: id (22) <= evictCount (87)

goroutine 338 [running]:
golang.org/x/net/http2/hpack.(*headerFieldTable).idToIndex(0xc0004cac80, 0xc0009731d0?)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220708220712-1185a9018129/http2/hpack/tables.go:119 +0xce
golang.org/x/net/http2/hpack.(*headerFieldTable).search(0xc0004cac80, {{0xc00107f460, 0xc}, {0xc0013511a0, 0x24}, 0x0})
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220708220712-1185a9018129/http2/hpack/tables.go:106 +0xe5
golang.org/x/net/http2/hpack.(*Encoder).searchTable(0xc0004cac80, {{0xc00107f460, 0xc}, {0xc0013511a0, 0x24}, 0x0})
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220708220712-1185a9018129/http2/hpack/encode.go:97 +0x88
golang.org/x/net/http2/hpack.(*Encoder).WriteField(0xc0004cac80, {{0xc00107f460, 0xc}, {0xc0013511a0, 0x24}, 0x0})
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220708220712-1185a9018129/http2/hpack/encode.go:62 +0x14a
google.golang.org/grpc/internal/transport.(*loopyWriter).writeHeader(0xc0004c9200, 0xfd, 0x0, {0xc000a0b440?, 0x8, 0xc0003e3e68?}, 0x424207?)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:684 +0x32a
google.golang.org/grpc/internal/transport.(*loopyWriter).originateStream(0xc0004c9200, 0xc000592100)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:671 +0x185
google.golang.org/grpc/internal/transport.(*loopyWriter).headerHandler(0xc0004c9200, 0xc00117fa90)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:659 +0x394
google.golang.org/grpc/internal/transport.(*loopyWriter).handle(0xc000481360?, {0x1375980?, 0xc00117fa90?})
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:831 +0x3e5
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0004c9200)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:539 +0x9e
google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/http2_client.go:415 +0x65
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/http2_client.go:413 +0x1eb1
```

but when i remove fiber to gin , not rise that evict issue 

so i think relate by fasthttp  if you know any relate case?

**Comment by erikdubbelboer** [comment]
But I don't see fasthttp in that stacktrace?

Can you share your code so I can have a look at how you are using fasthttp?
