### ISSUE TITLE
fatal error: sync: unlock of unlocked mutex

### ISSUE THREAD

**Issue by aishwaryakc508** [valyala/fasthttp#1373]
I am getting following error at random when sending request .

```
fatal error: sync: unlock of unlocked mutex

goroutine 2517 [running]:
runtime.throw({0xb7ec67, 0xc0018cf4a0})
        /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc0008c76b0 sp=0xc0008c7680 pc=0x434811
sync.throw({0xb7ec67, 0xc0018cf4a0})
        /usr/local/go/src/runtime/panic.go:1184 +0x1e fp=0xc0008c76d0 sp=0xc0008c76b0 pc=0x45f51e
sync.(*Mutex).unlockSlow(0xc00108fba0, 0xffffffff)
        /usr/local/go/src/sync/mutex.go:196 +0x3c fp=0xc0008c76f8 sp=0xc0008c76d0 pc=0x47915c
sync.(*Mutex).Unlock(...)
        /usr/local/go/src/sync/mutex.go:190
github.com/valyala/fasthttp.(*Client).mCleaner(0xc00108fb00, 0xc0018cf4a0)
        /home/ec2-user/go/src/github.com/valyala/fasthttp/client.go:584 +0x13f fp=0xc0008c77c0 sp=0xc0008c76f8 pc=0x8cc61f
github.com/valyala/fasthttp.(*Client).Do·dwrap·2()
        /home/ec2-user/go/src/github.com/valyala/fasthttp/client.go:541 +0x2a fp=0xc0008c77e0 sp=0xc0008c77c0 pc=0x8cc46a
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0008c77e8 sp=0xc0008c77e0 pc=0x463e41
created by github.com/valyala/fasthttp.(*Client).Do
        /home/ec2-user/go/src/github.com/valyala/fasthttp/client.go:541 +0x5a5
```

Following is the snippment of my code.

```
func (c *FollowRedirectClient) DoTimeout(req *fasthttp.Request, resp *fasthttp.Response, timeout time.Duration) (error error, initialResp *fasthttp.Response) {
	var redirectCount = 0
	for {
		if redirectCount == 15 { // setting max redirect count to 15"
			return fmt.Errorf("Redirect count exceeded limit 15"), nil
		}

		redirectCount += 1
		//c.Client.TLSConfig = &tls.Config{InsecureSkipVerify: true}
		c.Client = fasthttp.Client{
			ReadTimeout:  time.Duration(180) * time.Second,
			WriteTimeout: time.Duration(180) * time.Second,
			//	MaxConnWaitTimeout:  time.Duration(180) * time.Second,
			//MaxConnDuration:     time.Duration(180) * time.Second,
			//MaxIdleConnDuration: time.Duration(180) * time.Second,
			TLSConfig: &tls.Config{InsecureSkipVerify: true},
		}

		if err := c.Client.DoTimeout(req, resp, timeout); err != nil {
			return err, nil
		}

		if redirectCount == 1 {
			// initialResp=resp         /// if this was directly done, memory address of resp would be set to initialResp, resp would be changed on redirect on loop and thus initialResp would also be changed as they are pointing to same memory address..
			placeholder := *resp       // get value of from memory address of - resp *fasthttp.Response
			initialResp = &placeholder // sets initialResp as memory address of placeholder so that initialResp becomes of type resp *fasthttp.Response
		}

		statusCode := resp.Header.StatusCode()
		if statusCode != fasthttp.StatusMovedPermanently &&
			statusCode != fasthttp.StatusFound &&
			statusCode != fasthttp.StatusSeeOther &&
			statusCode != fasthttp.StatusTemporaryRedirect &&
			statusCode != fasthttp.StatusPermanentRedirect {
			break
		}

		location := resp.Header.PeekBytes(strLocation)

		if len(location) == 0 {
			return fmt.Errorf("Redirect with missing Location header"), nil
		}

		u := req.URI()
		u.UpdateBytes(location)

	}
	return nil, initialResp
}

func get(url string, ssl bool, timeout int) (initialResponse *fasthttp.Response, resp *fasthttp.Response) {
	c := FollowRedirectClient{}

	req := fasthttp.AcquireRequest()
	req.Header.Set("accept", "*/*")
	req.Header.SetUserAgent("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36")
	resp = fasthttp.AcquireResponse()

	req.SetRequestURI(site(url, ssl))
	err, initialResponse := c.DoTimeout(req, resp, time.Duration(timeout)*time.Second)
	if err != nil {
		log.Println(url, err)
	}
	return initialResponse, resp
}
```

**Comment by erikdubbelboer** [comment]
Interesting. This seems to be impossible to me. Which version of Go are you using and which version of fasthttp?

**Comment by aishwaryakc508** [comment]
Hello @erikdubbelboer ,

Thank you for your quick response. 

I have tried on following two version of Go and getting same error. 

Go version  : `go1.19 linux/amd64` and `go1.17 linux/amd64`

fasthttp : latest version `v1.40.0`

**Comment by erikdubbelboer** [comment]
What happens when you run `go vet ./...`?

The mutex Lock/Unlock section is really simple and impossible to go wrong: https://github.com/valyala/fasthttp/blob/2f1e949d91d0ba1817afd80d7c981fafe7154774/client.go#L573-L584

This is caused by your `FollowRedirectClient.Client` being a `fasthttp.Client` instead of `*fasthttp.Client` (pointer). And you overwriting it while there are still goroutines using the old value.

You should change `FollowRedirectClient.Client` into a pointer. And you should only set c.Client once. If you reset it each time it's impossible for fasthttp to use keep-alive connections as it is loosing the client state each time.
