### ISSUE TITLE
panic: runtime error: index out of range [1] with length 0

### ISSUE THREAD

**Issue by merdw** [valyala/fasthttp#1464]
I run it as a maximum of 300 connections in same time, it works up to a point, but at a random time it panics and the program closes.

```
panic: runtime error: index out of range [1] with length 0

goroutine 9951 [running]:
github.com/valyala/fasthttp.(*RequestHeader).AppendBytes(0xc000092380, {0xc002473500?, 0x0, 0x0?})
        C:/Users/Mert/go/pkg/mod/github.com/valyala/fasthttp@v1.43.0/header.go:2494 +0x1cb0
github.com/valyala/fasthttp.(*RequestHeader).Header(...)
        C:/Users/Mert/go/pkg/mod/github.com/valyala/fasthttp@v1.43.0/header.go:2416
github.com/valyala/fasthttp.(*RequestHeader).Write(0xc000092380, 0x1?)
        C:/Users/Mert/go/pkg/mod/github.com/valyala/fasthttp@v1.43.0/header.go:2396 +0x3a
github.com/valyala/fasthttp.(*Request).Write(0xc000092380, 0x542cf8?)
        C:/Users/Mert/go/pkg/mod/github.com/valyala/fasthttp@v1.43.0/http.go:1541 +0xc67
github.com/valyala/fasthttp.(*HostClient).doNonNilReqResp(0xc0002a2000, 0xc000092380, 0xc00034c8c0)
        C:/Users/Mert/go/pkg/mod/github.com/valyala/fasthttp@v1.43.0/client.go:1374 +0x57d
github.com/valyala/fasthttp.(*HostClient).do(0xc00234fd00?, 0x458365?, 0xc00034c8c0)
        C:/Users/Mert/go/pkg/mod/github.com/valyala/fasthttp@v1.43.0/client.go:1289 +0x79
github.com/valyala/fasthttp.(*HostClient).Do(0xc0002a2000, 0xc000092380, 0xc0000a8090?)
        C:/Users/Mert/go/pkg/mod/github.com/valyala/fasthttp@v1.43.0/client.go:1236 +0x91
github.com/valyala/fasthttp.(*Client).Do(0x72c7a0, 0xc000092380, 0x2ec?)
        C:/Users/Mert/go/pkg/mod/github.com/valyala/fasthttp@v1.43.0/client.go:543 +0x5bf
main.Post({0xc0001fd760, 0x6})
        C:/Users/Mert/GolandProjects/GmailCheckermerd/main.go:44 +0x3e5
main.main.func1({0xc0001fd760, 0x6})
        C:/Users/Mert/GolandProjects/GmailCheckermerd/main.go:107 +0x65
created by main.main
        C:/Users/Mert/GolandProjects/GmailCheckermerd/main.go:105 +0x43b
exit status 2
```

**Comment by erikdubbelboer** [comment]
Can you share your code? I'm guessing you are (re)using struct or byte slices when it's not allowed.

**Comment by merdw** [comment]
> 

I used releaserequest twice now I deleted one it works fine now, thank you.
