### ISSUE TITLE
Nil pointer dereference when compressing handler

### ISSUE THREAD

**Issue by abenz1267** [valyala/fasthttp#153]
Hello,

i'm facing following problem: when i compress the handler with CompressHandler(h), i'm getting " panic: runtime error: invalid memory address or nil pointer dereference "

    func NewUser(ctx *fasthttp.RequestCtx, _ fasthttprouter.Params) {

	args := &fasthttp.Args{}

	args.Add("response", string(ctx.FormValue("g-recaptcha-response")))
	args.Add("secret", "6Lf4piUTAAAAADpgK1E3i2_MOWNrMb3EqvwGkY4O")

	url := "https://www.google.com/recaptcha/api/siteverify"

	request := &fasthttp.Client{}

	status, _, err := request.Post(nil, url, args)
	if err != nil {
		fmt.Println(err)
	}
	if status != 200 {
		ctx.SetStatusCode(fasthttp.StatusBadRequest)
	}

	hashedPassword := hash(string(ctx.FormValue("password")))

	token, err := GenerateRandomString(32)
	if err != nil {
		panic(err)
	}

	time := int32(time.Now().Unix())
	uid := time + int32(rand.Intn(1000))

	_, sqlerror := db.Query("INSERT INTO users (uid, email, password, token, registered, nickname) VALUES ($1,$2,$3,$4,$5,$6)", uid, string(ctx.FormValue("email")), hashedPassword, token, time, string(ctx.FormValue("nickname")))
	if sqlerror == nil {
		ctx.SetStatusCode(fasthttp.StatusOK)

		fmt.Println("New User")
	} else {
		fmt.Println(sqlerror)
		ctx.SetStatusCode(fasthttp.StatusInternalServerError)
	}
	//EMAIL
    }

Error:

    [gin] listening on port 3000
    New User
    2016/07/30 23:13:34 panic: runtime error: invalid memory address or nil pointer dereference
    Stack trace:
    goroutine 20 [running]:
    runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
    github.com/valyala/fasthttp.(*workerPool).workerFunc.func1(0xc820182000, 0xc8203d3ec0)
	/home/andrej/work/src/github.com/valyala/fasthttp/workerpool.go:207 +0x53
    panic(0x978500, 0xc82000a150)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
    github.com/valyala/fasthttp.(*byteBufferPool).Release(0xcfc4b0, 0x0)
	/home/andrej/work/src/github.com/valyala/fasthttp/bytebuffer.go:86 +0x18
    github.com/valyala/fasthttp.(*Response).gzipBody(0xc820154708, 0xffffffffffffffff, 0x0, 0x0)
	/home/andrej/work/src/github.com/valyala/fasthttp/http.go:1141 +0x322
    github.com/valyala/fasthttp.CompressHandlerLevel.func1(0xc820154480)
	/home/andrej/work/src/github.com/valyala/fasthttp/server.go:354 +0x111
    github.com/valyala/fasthttp.(*Server).serveConn(0xc820146140, 0x7f9cf0046690, 0xc82013e040, 0x0, 0x0)
	/home/andrej/work/src/github.com/valyala/fasthttp/server.go:1494 +0x963
    github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0x7f9cf0046690, 0xc82013e040, 0x0, 0x0)
	/home/andrej/work/src/github.com/valyala/fasthttp/server.go:1223 +0x42
    github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc820182000, 0xc820140280)
	/home/andrej/work/src/github.com/valyala/fasthttp/workerpool.go:224 +0x11c
    github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc820182000, 0xc820140280, 0x87d300, 0xc820140280)
	/home/andrej/work/src/github.com/valyala/fasthttp/workerpool.go:183 +0x2b
    created by github.com/valyala/fasthttp.(*workerPool).getCh
	/home/andrej/work/src/github.com/valyala/fasthttp/workerpool.go:185 +0x1e9
    2016/07/30 23:13:34 http: proxy error: EOF

It somehow fails to set the statuscode via " ctx.SetStatusCode(fasthttp.StatusOK) " when being compressed.

I'm using fasthttprouter.

Regards

**Comment by abenz1267** [comment]
ctx.SuccessString("text", "ok")

Solves it
