### ISSUE TITLE
Slice bounds out of range in appendBodyFixedSize

### ISSUE THREAD

**Issue by TheKavorka** [valyala/fasthttp#1588]
The appendBodyFixedSize function can panic when dstlen is larger than math.MaxInt32. This results in a panic slice out of range as shown in the output below.

```
panic: runtime error: slice bounds out of range [:10737418240] with capacity 2147483648

goroutine 200 [running]:
github.com/valyala/fasthttp.appendBodyFixedSize(0xc0c900e420, 0xc0a6000000, 0x0, 0x20000, 0x280000000, 0xca1580, 0xc03c332920, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.20.0/http.go:2011 +0x335
github.com/valyala/fasthttp.readBody(0xc0c900e420, 0x280000000, 0x0, 0xc0a6000000, 0x0, 0x20000, 0xc00f310ac0, 0xc1162c39059fd361, 0x725ff1831, 0x12b88e0, ...)
        /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.20.0/http.go:1928 +0x71
github.com/valyala/fasthttp.(*Response).ReadLimitBody(0xc001ddc780, 0xc0c900e420, 0x0, 0xc0c900e420, 0x0)
        /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.20.0/http.go:1231 +0x132
github.com/valyala/fasthttp.(*HostClient).doNonNilReqResp(0xc010098300, 0xc0ef98c900, 0xc001ddc780, 0xe, 0x600, 0x1)
        /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.20.0/client.go:1409 +0x35f
github.com/valyala/fasthttp.(*HostClient).do(0xc010098300, 0xc0ef98c900, 0xc001ddc780, 0x0, 0xc0a7595490, 0xe)
        /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.20.0/client.go:1311 +0x57
github.com/valyala/fasthttp.(*HostClient).Do(0xc010098300, 0xc0ef98c900, 0xc001ddc780, 0xc0098ed800, 0xc0e0587000)
        /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.20.0/client.go:1258 +0xa5
github.com/assetnote/kiterunner/pkg/http.doRequestFollowRedirects(0xc010098300, 0xc0ef98c900, 0xc001ddc780, 0xc00ef55760, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/kiterunner/kiterunner/pkg/http/client.go:163 +0x866
github.com/assetnote/kiterunner/pkg/http.DoClient(0xc010098300, 0xc0001b0270, 0xc04a0e3290, 0xc00ef55760, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/kiterunner/kiterunner/pkg/http/client.go:123 +0x205
github.com/assetnote/kiterunner/pkg/kiterunner.handleRequest(0xdf38e0, 0xc00193c500, 0xc0037045c0, 0xc0ab961a40, 0xc00ef55740, 0x20, 0x194)
        /home/runner/work/kiterunner/kiterunner/pkg/kiterunner/kiterunner.go:280 +0x433
github.com/assetnote/kiterunner/pkg/kiterunner.(*Engine).RunAsync.func2(0xc0a5747220, 0xc0abaf4960, 0xc020d036e0, 0xc020d036d0, 0xc0ab961a40)
        /home/runner/work/kiterunner/kiterunner/pkg/kiterunner/kiterunner.go:421 +0x1ca
created by github.com/assetnote/kiterunner/pkg/kiterunner.(*Engine).RunAsync
        /home/runner/work/kiterunner/kiterunner/pkg/kiterunner/kiterunner.go:400 +0x205
```

The round2 function returns math.MaxInt32 when x is sufficiently large as seen in the code below on line 2356.

https://github.com/valyala/fasthttp/blob/0d0bbfee5a8dd12a82e442d3cbb11e56726dd06e/http.go#L2342-L2360

round2 is used to initialize a []byte in appendBodyFixedSize on line 2232. the dstlen is then used as the upper bound when assigning dst in line 2236.

https://github.com/valyala/fasthttp/blob/0d0bbfee5a8dd12a82e442d3cbb11e56726dd06e/http.go#L2224-L2255

For my purposes the following hack fixed the issue however I think the issue is actually with the round2 function and may affect more functions depending on where that is used.

```
func appendBodyFixedSize(r *bufio.Reader, dst []byte, n int) ([]byte, error) {
        if n == 0 {
                return dst, nil
        }

        offset := len(dst)
        dstLen := offset + n

        if cap(dst) < dstLen {
                r2 := round2(dstLen)
                if r2 == math.MaxInt32 {
                        return dst, ErrBodyTooLarge
                }
                b := make([]byte, r2)
                copy(b, dst)
                dst = b
        }
        dst = dst[:dstLen]

        for {
                nn, err := r.Read(dst[offset:])
                if nn <= 0 {
                        switch {
                        case errors.Is(err, io.EOF):
                                return dst[:offset], io.ErrUnexpectedEOF
                        case err != nil:
                                return dst[:offset], err
                        default:
                                return dst[:offset], fmt.Errorf("bufio.Read() returned (%d, nil)", nn)
                        }
                }
                offset += nn
                if offset == dstLen {
                        return dst, nil
                }
        }
}
```

**Comment by erikdubbelboer** [comment]
Should be fixed in https://github.com/valyala/fasthttp/commit/1c85d43dfea23d49285c8248aff906c965062031
