### ISSUE TITLE
Bug: When deadline from HeaderReceived，panic assert may occur in logic.  

### ISSUE THREAD

**Issue by newacorn** [valyala/fasthttp#1815]
https://github.com/valyala/fasthttp/blob/ed6a27a88e9f759283a1783be68d469dbb4078b4/server.go#L2260
If I understand correctly, the panic assertion here assumes that this situation should logically never occur. However, in reality, it can indeed happen.

root reason: set deadline on a closed net.Conn return a error.
## A condition for occurring
let readtimeout for example
Server.ReadTimeout is zero, but Server.HeaderReceived.ReadTimeout is not.
net.Conn state change window from idle to active. at the same time server shutdown called.
## Test
```go
func TestSeverSetReadDeadlineUseHeaderReceivedBug(t *testing.T) {
	const clientConnCount = 500
	var cliConnSecReqNotify = make(chan struct{})
	s := fasthttp.Server{HeaderReceived: func(header *fasthttp.RequestHeader) fasthttp.RequestConfig {
		return fasthttp.RequestConfig{ReadTimeout: time.Hour}
	}}
	go func() {
		s.Handler = func(ctx *fasthttp.RequestCtx) {
			defer func() {
				if recover() != nil {
					t.Error(recover())
				}
			}()
			_, _ = ctx.WriteString("hello world")
		}
		err := s.ListenAndServe(":7070")
		if err != nil {
			log.Println(err)
		}
		time.Sleep(time.Hour)
	}()
	time.Sleep(time.Millisecond * 100)
	wg := sync.WaitGroup{}
	fistRqSend := sync.WaitGroup{}
	for i := 0; i < clientConnCount; i++ {
		wg.Add(1)
		fistRqSend.Add(1)
		time.Sleep(time.Millisecond * 10)
		go func() {
			defer wg.Done()
			cliCon, err := net.Dial("tcp", ":7070")
			if err != nil {
				log.Println(err)
				fistRqSend.Done()
				return
			}
			httpReqStr := "GET / HTTP/1.1\r\n\r\n"
			_, err = cliCon.Write([]byte(httpReqStr))
			if err != nil {
				log.Println(err)
			}
			resp := AcquireResponse()
			defer func() { ReleaseResponse(resp) }()
			buf := bufio.NewReader(cliCon)
			err = resp.Read(buf)
			if err != nil {
				log.Println(err)
			}
			assert.Eq(t, resp.Body(), []byte("hello world"))
			fistRqSend.Done()
			fistReqSuccessCount.Add(1)
			<-cliConnSecReqNotify
			cliCon.Write([]byte("GET / HTTP/1.1\r\n\r\n"))
			cliCon.Write([]byte("\r\n"))
			buf.Reset(cliCon)
			resp.Reset()
			resp.Read(buf)
		}()
	}
	fistRqSend.Wait()
	log.Println(fistReqSuccessCount.Load())
	close(cliConnSecReqNotify)
	time.Sleep(time.Millisecond)
	s.Shutdown()
	wg.Wait()
}
```
### output
panic occuring almost every time.
```
❯ go test -v -run=TestSeverSetReadDeadlineBug$ .
=== RUN   TestSeverSetReadDeadlineBug
tmp_test.go:160: 500
panic: BUG: error in SetReadDeadline(2024-07-31 16:52:13.48336 +0800 CST m=+3605.319380140): set tcp4 127.0.0.1:7070: use of closed network connection

goroutine 758 [running]:
github.com/newacorn/fasthttp.(*Server).serveConn(0xc000172248, {0x116057e0, 0xc0005f66f0})
	/Users/acorn/workspace/programming/golang/wx/fasthttp/server.go:2317 +0x220a
github.com/newacorn/fasthttp.(*workerPool).workerFunc(0xc00009c000, 0xc00020cdc0)
	/Users/acorn/workspace/programming/golang/wx/fasthttp/workerpool.go:224 +0xa4
github.com/newacorn/fasthttp.(*workerPool).getCh.func1()
	/Users/acorn/workspace/programming/golang/wx/fasthttp/workerpool.go:196 +0x32
created by github.com/newacorn/fasthttp.(*workerPool).getCh in goroutine 199
	/Users/acorn/workspace/programming/golang/wx/fasthttp/workerpool.go:195 +0x190
FAIL	github.com/newacorn/fasthttp	5.332s
FAIL
```

**Comment by newacorn** [comment]
In this case, it's better to simply break out of the for loop. This boundary issue cannot be resolved, especially since `br` is a buffer.
We cannot guarantee that when the shutdown closes the connection, our `br` has not read any content. During the peek, it is possible to read a complete request header into the buffer. Therefore, even if we immediately switch the state to active after the peek, it won't help.
