### ISSUE TITLE
Request with header "Expect: 100-continue " lead to goroutine leak

### ISSUE THREAD

**Issue by lepdou** [valyala/fasthttp#1834]
I use fasthttp as http server. When run a few days, the number of goroutine increase all the time. I dump goroutine, found many goroutine block on "IO wait".

```
goroutine 8453253192 [IO wait, 1757 minutes]:
internal/poll.runtime_pollWait(0x7fd3f7b5a918, 0x72)
        runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc49f941a00?, 0xc463a20000?, 0x0)
        internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc49f941a00, {0xc463a20000, 0x725a, 0x10000})
        internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc49f941a00, {0xc463a20000?, 0x555bd55d9606?, 0xc49f941a00?})
        net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc273dff430, {0xc463a20000?, 0x19?, 0x19?})
        net/net.go:183 +0x45
bufio.(*Reader).Read(0xc423172e40, {0xc463a20000, 0x725a, 0xc12f946000?})
        bufio/bufio.go:222 +0x106
github.com/valyala/fasthttp.appendBodyFixedSize(0xc2ee67dbd0?, {0xc463a20000?, 0xc0c284b710?, 0x0?}, 0x0?)
        github.com/valyala/fasthttp@v1.31.0/http.go:2003 +0x114
github.com/valyala/fasthttp.readBody(0xc2ee67dc30?, 0x555bd570d015?, 0xc000cfe570?, {0xc463a20000?, 0x555bd570ccc2?, 0xc273dff430?})
        github.com/valyala/fasthttp@v1.31.0/http.go:1914 +0x65
github.com/valyala/fasthttp.(*Request).ContinueReadBody(0xc44d757080, 0x555bd7236fb0?, 0x400000, {0xc2ee67dc89?, 0x555bd723575c?, 0x5?})
        github.com/valyala/fasthttp@v1.31.0/http.go:1127 +0x2d2
github.com/valyala/fasthttp.(*Server).serveConn(0xc000cfe400, {0x555bd69b4690?, 0xc273dff430})
        github.com/valyala/fasthttp@v1.31.0/server.go:2253 +0x1075
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00054f360, 0xc345eedfa0)
        github.com/valyala/fasthttp@v1.31.0/workerpool.go:223 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        github.com/valyala/fasthttp@v1.31.0/workerpool.go:195 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
        github.com/valyala/fasthttp@v1.31.0/workerpool.go:194 +0x1b0
```

![image](https://github.com/user-attachments/assets/7210e9b2-bc06-4cc8-8e75-6363734d3a30)

After I read the source code, the reason may be is client send request with header "Expect: 100-continue " ,after server send back 'HTTP/1.1 100 Continue' response. But client not continue send body as expected. So server wait request's body all the time and not release gorouine.

![image](https://github.com/user-attachments/assets/921f5e23-f5e3-4f91-9ef4-fb9f3d3e10f7)

My question is setting ReadTimeout params can resolve the problem? like this:

```
httpSvr = &fasthttp.Server{
			ReadTimeout:        60 * time.Second, # new params
			WriteTimeout:       60  * time.Second,
			IdleTimeout:       300 * time.Second
		}
```

Thank you ~

**Comment by erikdubbelboer** [comment]
Yes, using `ReadTimeout` is a good fix for that. I would always recommend using timeouts if you are interfacing with clients/servers that you don't have control over and that can misbehave like this.

**Comment by lepdou** [comment]
Thanks for your replay.
