### ISSUE TITLE
Unhandled panic on opening .onion domains

### ISSUE THREAD

**Issue by asciimoo** [valyala/fasthttp#196]
Example code:
```go
var dst []byte
fasthttp.Get(dst, "http://xy.onion/")
fmt.Println(string(dst))
```
Output:
```
panic: BUG: DialFunc returned (nil, nil)

goroutine 1 [running]:
panic(0x6666a0, 0xc42015a200)
        /go/src/runtime/panic.go:500 +0x1a1
github.com/valyala/fasthttp.dialAddr(0xc420011540, 0xb, 0x6efeb8, 0x0, 0x0, 0x839701, 0x32e7500e000, 0x0, 0x1)
        /src/github.com/valyala/fasthttp/client.go:1447 +0x1d5
github.com/valyala/fasthttp.(*HostClient).dialHostHard(0xc4200968c0, 0x6efe90, 0xc4200968c0, 0x0, 0xc42004b8f8)
        /src/github.com/valyala/fasthttp/client.go:1402 +0x1bd
github.com/valyala/fasthttp.(*HostClient).acquireConn(0xc4200968c0, 0x0, 0x8383c0, 0xd0)
        /src/github.com/valyala/fasthttp/client.go:1178 +0xee
github.com/valyala/fasthttp.(*HostClient).doNonNilReqResp(0xc4200968c0, 0xc4200a2b00, 0xc42010c0f0, 0x8, 0xd600a8c2be5e8962, 0x0)
        /src/github.com/valyala/fasthttp/client.go:1025 +0xb1
github.com/valyala/fasthttp.(*HostClient).do(0xc4200968c0, 0xc4200a2b00, 0xc42010c0f0, 0x4a53b5, 0x4571b0, 0xc42004bad8)
        /src/github.com/valyala/fasthttp/client.go:1002 +0x51
github.com/valyala/fasthttp.(*HostClient).Do(0xc4200968c0, 0xc4200a2b00, 0xc42010c0f0, 0xc42000d3e0, 0xc420011550)
        /src/github.com/valyala/fasthttp/client.go:971 +0x68
github.com/valyala/fasthttp.(*Client).Do(0x838500, 0xc4200a2b00, 0xc42010c0f0, 0x0, 0x10)
        /src/github.com/valyala/fasthttp/client.go:412 +0x1fc
github.com/valyala/fasthttp.doRequestFollowRedirects(0xc4200a2b00, 0x0, 0x0, 0x0, 0x6cdf13, 0x10, 0x804dc0, 0x838500, 0x0, 0x8, ...)
        /src/github.com/valyala/fasthttp/client.go:766 +0x19e
github.com/valyala/fasthttp.clientGetURL(0x0, 0x0, 0x0, 0x6cdf13, 0x10, 0x804dc0, 0x838500, 0xc4200114c0, 0xc4200113b8, 0x4, ...)
        /src/github.com/valyala/fasthttp/client.go:665 +0xa4
github.com/valyala/fasthttp.(*Client).Get(0x838500, 0x0, 0x0, 0x0, 0x6cdf13, 0x10, 0x8, 0x839780, 0x3, 0x4, ...)
        /src/github.com/valyala/fasthttp/client.go:243 +0x7c
github.com/valyala/fasthttp.Get(0x0, 0x0, 0x0, 0x6cdf13, 0x10, 0x24, 0xd4, 0xc4200950e0, 0x0, 0x0, ...)
        /src/github.com/valyala/fasthttp/client.go:100 +0x6c
main.main()
        /src/github.com/asciimoo/morty/morty.go:637 +0x66
```

**Comment by valyala** [comment]
@asciimoo , could you verify that the issue has been fixed now?

**Comment by valyala** [comment]
It looks like that `.onion` domains resolve only to `ipv6` addresses, which are ignored by fasthttp client by default. Try passing [DialDualStack](https://godoc.org/github.com/valyala/fasthttp#DialDualStack) to [Client.Dial](https://godoc.org/github.com/valyala/fasthttp#Client):

```go
c := &fasthttp.Client{
    Dial: DialDualStack,
}
c.Get(nil, "http://foobar.onion")
```

**Comment by asciimoo** [comment]
@valyala thank you the fast response and the fix. It works well.
