### ISSUE TITLE
DNS resolve error: no such host

### ISSUE THREAD

**Issue by lunemec** [valyala/fasthttp#204]
Hello again,

as we discussed in #189, I was getting a ConnectionClosed errors on my "Proxy" implementation, so I tried to create a Retryer. This is what I came up with:
```go
package retry

import (
	"errors"
	"time"

	"github.com/valyala/fasthttp"
)

type DoFuncType func(*fasthttp.Request, *fasthttp.Response, time.Duration) error

var (
	MaxRetries      = 10
	MaxRetriesError = errors.New("MaxRetires reached, unable to reach upstream.")
	MaxBodySize     = 1024 * 1024
	RetryError      = errors.New("Cannot retry this request, body is streamed.")
)

func DoRetry(request *fasthttp.Request, response *fasthttp.Response, timeout time.Duration) error {
	return doRetryWithFunc(fasthttp.DoTimeout, request, response, timeout)
}

func doRetryWithFunc(doFunc DoFuncType, request *fasthttp.Request, response *fasthttp.Response, timeout time.Duration) error {
	if request.IsBodyStream() {
		return RetryError
	}

	timeStart := time.Now()
	originalBody := make([]byte, len(request.Body()))
	copy(originalBody, request.Body())
	err := doFunc(request, response, timeout)

	switch err {
	case fasthttp.ErrConnectionClosed:
		timeoutRetry := timeout - time.Since(timeStart)
		return call(doFunc, request, originalBody, response, timeoutRetry, MaxRetries)
	case nil:
		return nil
	default:
		return err
	}
}

func call(doFunc DoFuncType, request *fasthttp.Request, originalBody []byte, response *fasthttp.Response, timeout time.Duration, retries int) error {
	if retries == 0 {
		return MaxRetriesError
	}
	timeStart := time.Now()
	request.SetBody(originalBody)
	request.SetConnectionClose()

	err := doFunc(request, response, timeout)
	if err == fasthttp.ErrConnectionClosed {
		timeoutRetry := timeout - time.Since(timeStart)
		err = call(doFunc, request, originalBody, response, timeoutRetry, retries-1)
	}
	return err
}
```

It is not efficient solution, as it copies the body and will not work on streams. However it is sufficient for my uses. However, I've started to get strange DNS lookup errors, even when `Request.URI.Host` is set to `localhost`. I tried compiling with `netgo` and `netcgo` but nothing changed. However, when I compile the code with `-race` detection on, the issue suddenly disappears.

Here is how I'm calling the `DoRetry`:
```go
request := fasthttp.AcquireRequest()
request.URI().SetHost(upstream)
request.Header.SetMethod("POST")
request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
request.SetBodyString(".... body ....")
request.URI().SetPath("/PATH")

fasthttp.ReleaseRequest(Ctx.Request)
Ctx.Request = request
err := retry.DoRetry(&Ctx.Request, &data.Ctx.Response, data.Timeout)
return err
```

This is traceback when I get `no such host`:
```go
  goroutine 60 [running]:
runtime/debug.Stack(0xc420015e40, 0x705b00, 0xc4201c2070)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/debug/stack.go:24 +0x79
lingea-validator/src/vendor/github.com/mgutz/logxi/v1.(*JSONFormatter).writeError(0xc420015e40, 0x705b00, 0xc4201c2070, 0x700bc0, 0xc420112a80)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/vendor/github.com/mgutz/logxi/v1/jsonFormatter.go:48 +0x70
lingea-validator/src/vendor/github.com/mgutz/logxi/v1.(*JSONFormatter).appendValue(0xc420015e40, 0x705b00, 0xc4201c2070, 0x45fb00, 0xc420112a80)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/vendor/github.com/mgutz/logxi/v1/jsonFormatter.go:61 +0xe0
lingea-validator/src/vendor/github.com/mgutz/logxi/v1.(*JSONFormatter).set(0xc420015e40, 0x705b00, 0xc4201c2070, 0x4cbad4, 0x3, 0x45fb00, 0xc420112a80)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/vendor/github.com/mgutz/logxi/v1/jsonFormatter.go:130 +0xd1
lingea-validator/src/vendor/github.com/mgutz/logxi/v1.(*JSONFormatter).Format(0xc420015e40, 0x6ffe00, 0xc42016ecb0, 0x7, 0x4dd3fb, 0x22, 0xc420112ac0, 0x4, 0x4)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/vendor/github.com/mgutz/logxi/v1/jsonFormatter.go:177 +0x537
lingea-validator/src/vendor/github.com/mgutz/logxi/v1.(*JSONFormatter).LogEntry(0xc420015e40, 0x7, 0x4dd3fb, 0x22, 0xc420112ac0, 0x4, 0x4, 0x0)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/vendor/github.com/mgutz/logxi/v1/jsonFormatter.go:198 +0xfb
lingea-validator/src/vendor/github.com/mgutz/logxi/v1.(*HappyDevFormatter).Format(0xc420106de0, 0x700500, 0xc420106ba0, 0x7, 0x4dd3fb, 0x22, 0xc420112ac0, 0x4, 0x4)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/vendor/github.com/mgutz/logxi/v1/happyDevFormatter.go:294 +0x318
lingea-validator/src/vendor/github.com/mgutz/logxi/v1.(*DefaultLogger).Log(0xc420010500, 0x7, 0x4dd3fb, 0x22, 0xc420112ac0, 0x4, 0x4)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/vendor/github.com/mgutz/logxi/v1/defaultLogger.go:117 +0xab
lingea-validator/src/vendor/github.com/mgutz/logxi/v1.(*DefaultLogger).Debug(0xc420010500, 0x4dd3fb, 0x22, 0xc420112ac0, 0x4, 0x4)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/vendor/github.com/mgutz/logxi/v1/defaultLogger.go:65 +0x66
lingea-validator/src/vendor/github.com/mgutz/logxi/v1.Debug(0x4dd3fb, 0x22, 0xc420112ac0, 0x4, 0x4)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/vendor/github.com/mgutz/logxi/v1/methods.go:10 +0x67
lingea-validator/src/controllers/health.(*ControllerTranslate).Process(0xc42022be08, 0xc4201c5a40, 0x10, 0x12a05f200)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/controllers/health/translate.go:63 +0x483
main.healthTranslator.func1(0xc4201c6000, 0x0, 0x0, 0x0)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/handlers.go:43 +0x66
lingea-validator/src/vendor/github.com/buaazp/fasthttprouter.(*Router).Handler(0xc420157dd0, 0xc4201c6000)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/vendor/github.com/buaazp/fasthttprouter/router.go:331 +0x902
lingea-validator/src/vendor/github.com/buaazp/fasthttprouter.(*Router).Handler-fm(0xc4201c6000)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/urls.go:19 +0x34
lingea-validator/src/vendor/github.com/valyala/fasthttp.TimeoutHandler.func1.1(0xc420151d10, 0xc4201c6000, 0xc4201c8060, 0xc42006ede0)
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/vendor/github.com/valyala/fasthttp/server.go:313 +0x30
created by lingea-validator/src/vendor/github.com/valyala/fasthttp.TimeoutHandler.func1
	/Users/lukas.nemec2/Documents/git/Go/src/lingea-validator/src/vendor/github.com/valyala/fasthttp/server.go:316 +0xed
```

However, in this traceback there is no mention of DNS resolv being done. Also my `upstream` is IP address, so no resolving should be done. At this point I believe there is error in my code somewhere with the fasthttp.Ctx.Request swapping (or the body), because I wasn't getting these errors in previous version of my code. Could you please point me somewhere in fasthttp where to look? I saw some DNS related stuff in tcpdialer.go, so I guess you implemented `everything` from scratch and my -netgo or -netcgo options made no difference...

What I found is, I have the Host set here:
```go
originalBody := make([]byte, len(request.Body()))
copy(originalBody, request.Body())

log.Info("Retry first request", "request", request. // <-- This is printed below..
err := doFunc(request, response, timeout)
```
Prints:
```go
17:14:19.779571 INF ~ Retry first request
   request: POST /PATH/ HTTP/1.1
User-Agent: fasthttp
Host: 10.0.24.246:9780
Content-Type: application/x-www-form-urlencoded
Content-Length: 466
```

But I added `println()` to tcpdialer.go:
```go
if e == nil {
	println("RESOLVING ADDR: ", addr)
	addrs, err := resolveTCPAddrs(addr, d.DualStack)
```

And this prints:
```go
RESOLVING ADDR:  :80
```

Which obviously fails at DNS lookup. What I have no clue is where this information gets lost. Since it is available right before calling `doFunc`, which is `fasthttp.DoTimeout`.

Any ideas?

Thank you!

**Comment by lunemec** [comment]
Oh, my fasthttp library version is: v20160617

**Comment by lunemec** [comment]
From what I found:

```go
func (c *HostClient) dialHostHard() (conn net.Conn, err error) {
	// attempt to dial all the available hosts before giving up.
	println("DialHostHard??")
	c.addrsLock.Lock()
	n := len(c.addrs)
	println("Len addrs: ", n)
	c.addrsLock.Unlock()

	if n == 0 {
		// It looks like c.addrs isn't initialized yet.
		n = 1
	}

	timeout := c.ReadTimeout + c.WriteTimeout
	if timeout <= 0 {
		timeout = DefaultDialTimeout
	}
	deadline := time.Now().Add(timeout)
	for n > 0 {
		addr := c.nextAddr()
		println("dialHostHard nextAddr: ", addr)
		conn, err = dialAddr(addr, c.Dial, c.DialDualStack, c.IsTLS, c.TLSConfig)
		if err == nil {
			return conn, nil
		}
		if time.Since(deadline) >= 0 {
			break
		}
		n--
	}
	return nil, err
}
```

This prints following:
```
DialHostHard??
Len addrs:  0
dialHostHard nextAddr:  :80
DIAL ADDR:  :80
RESOLVING ADDR:  :80
```

However, this happens in the second request, or after few requests. In the working request, this prints:
```
DialHostHard??
Len addrs:  0
dialHostHard nextAddr:  10.0.24.246:9780
DIAL ADDR:  10.0.24.246:9780
RESOLVING ADDR:  10.0.24.246:9780
```

So somehow `c.nextAddr()` returns " :80" ... but I have no idea if this is caused by my misuse of fasthttp or is simply a bug (probably already fixed now in master).

**Comment by lunemec** [comment]
Tried with current master, same issue.

**Comment by sickyoon** [comment]
I've tracked down the issue to `uri.go` where it is unable to get host from URL.
URL parser looks little flimsy and when you pass invalid URL, it will just die like that.
Check your URI. It's very likely that you are passing invalid URI like this: 
 `http:/my-site.com/asdf`
