### ISSUE TITLE
fasthttp panicking when no route is defined

### ISSUE THREAD

**Issue by debraj-manna** [valyala/fasthttp#227]
fasthttp is panicking when no route is defined. The code to repro the issue is below:-

```go
package main

import (
	"fmt"
	"github.com/buaazp/fasthttprouter"
	"github.com/valyala/fasthttp"
	"log"
)

func Hello(ctx *fasthttp.RequestCtx) {
	id := ctx.UserValue("id").(string)
	fmt.Fprint(ctx, fmt.Sprintf("%s\n", id))
}

func main() {
	//initRedis()
	router := fasthttprouter.New()
	router.POST("/:id", Hello)
	log.Fatal(fasthttp.ListenAndServe(":7890", router.Handler))
}
```

Then send a curl request like below:-

```bash
curl -XPOST "http://localhost:7890/2121"
```

The stack-trace is like below:-

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x49c9a2]

goroutine 19 [running]:
panic(0x6ffda0, 0xc42000c0e0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/valyala/fasthttp.(*RequestCtx).SetUserValue(0x0, 0x76db37, 0x2, 0x6e8780, 0xc420324f40)
    /home/jab/go/src/github.com/jab/JSes/_libs/src/bitbucket.org/myn/ses-ser/_libs/src/github.com/valyala/fasthttp/server.go:461 +0x22
github.com/buaazp/fasthttprouter.(*node).getValue(0xc420014c80, 0xc4202fd767, 0x7, 0x0, 0xc420074578, 0x7500000000)
    /home/jab/go/src/github.com/jab/JSes/_libs/src/bitbucket.org/myn/ses-ser/_libs/src/github.com/buaazp/fasthttprouter/tree.go:364 +0x1c7
github.com/buaazp/fasthttprouter.(*Router).allowed(0xc4201835f0, 0xc4202fd740, 0x2e, 0xc42004fc38, 0x4, 0x27, 0x2f)
    /home/jab/go/src/github.com/jab/JSes/_libs/src/bitbucket.org/myn/ses-ser/_libs/src/github.com/buaazp/fasthttprouter/router.go:273 +0x13d
github.com/buaazp/fasthttprouter.(*Router).Handler(0xc4201835f0, 0xc42000e900)
    /home/jab/go/src/github.com/jab/JSes/_libs/src/bitbucket.org/myn/ses-ser/_libs/src/github.com/buaazp/fasthttprouter/router.go:353 +0x23e
github.com/buaazp/fasthttprouter.(*Router).Handler-fm(0xc42000e900)
    /home/jab/go/src/github.com/jab/JSes/main.go:32 +0x34
github.com/valyala/fasthttp.CompressHandlerLevel.func1(0xc42000e900)
    /home/jab/go/src/github.com/jab/JSes/_libs/src/bitbucket.org/myn/ses-ser/_libs/src/github.com/valyala/fasthttp/server.go:345 +0x3f
github.com/valyala/fasthttp.(*Server).serveConn(0xc420098000, 0x8d41c0, 0xc420030448, 0xc42008e501, 0xc420080101)
    /home/jab/go/src/github.com/jab/JSes/_libs/src/bitbucket.org/myn/ses-ser/_libs/src/github.com/valyala/fasthttp/server.go:1533 +0x573
github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0x8d41c0, 0xc420030448, 0xc42004ff38, 0x1)
    /home/jab/go/src/github.com/jab/JSes/_libs/src/bitbucket.org/myn/ses-ser/_libs/src/github.com/valyala/fasthttp/server.go:1250 +0x3e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc42008e580, 0xc42012ef60)
    /home/jab/go/src/github.com/jab/JSes/_libs/src/bitbucket.org/myn/ses-ser/_libs/src/github.com/valyala/fasthttp/workerpool.go:210 +0xde
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc42008e580, 0xc42012ef60, 0x6d9e40, 0xc42012ef60)
    /home/jab/go/src/github.com/jab/JSes/_libs/src/bitbucket.org/myn/ses-ser/_libs/src/github.com/valyala/fasthttp/workerpool.go:182 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
    /home/jab/go/src/github.com/jab/JSes/_libs/src/bitbucket.org/myn/ses-ser/_libs/src/github.com/valyala/fasthttp/workerpool.go:184 +0x111
```

- Go Version 1.7

Can this be handled gracefully with an error message saying no route exists?

**Comment by erikdubbelboer** [comment]
Whatever this was it seems to have been fixed as I can't reproduce it.
