### ISSUE TITLE
Q: Is this a a data race?

### ISSUE THREAD

**Issue by mr-moon** [valyala/fasthttp#333]
Having a really simple request handler:

```
requestHandler := func(ctx *fasthttp.RequestCtx) {
	uri := string(ctx.RequestURI()[:])

	if len(uri) > 7 && uri[0:7] == "/datadb" {

		ctx.Response.Header.Set("Access-Control-Allow-Origin", "*")
		ctx.Response.Header.Set("Access-Control-Allow-Methods", "GET")
		ctx.Response.Header.Set("Access-Control-Max-Age", "0")
		ctx.Response.Header.Set("Cache-Control", "no-cache, no-store, must-revalidate")
		ctx.Response.Header.Set("Pragma", "no-cache")
		ctx.Response.Header.Set("Expires", "Wed, 21 Oct 2015 07:28:00 GMT")

		chunk = append(chunk, uri)
	}
}
```

`chunk` var is a global `[]string` variable;

I sometimes end up having my app exiting with:
```
goroutine 65676 [IO wait]:
internal/poll.runtime_pollWait(0x7fd9b6265840, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc427144d98, 0x72, 0xffffffffffffff00, 0x86c800, 0x869458)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc427144d98, 0xc428bb6800, 0x400, 0x400)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc427144d80, 0xc428bb6800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc427144d80, 0xc428bb6800, 0x400, 0x400, 0xc42014f400, 0x0, 0x412e16)
        /usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42309b970, 0xc428bb6800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc4286f32f0, 0x7fd9b9483128, 0xc42309b970, 0x5, 0xc42309b970, 0x412ead)
        /usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc420b74a80, 0x71cd17, 0xc420b74ba0, 0xc42001f6b8)
        /usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc420b74a80, 0xc423395000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).fill(0xc421235020)
        /usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc421235020, 0x1, 0xc4217de800, 0x7fd9b9483100, 0xc427d21cb0, 0x658716, 0x6e2e40)
        /usr/local/go/src/bufio/bufio.go:129 +0x3a
github.com/valyala/fasthttp.(*RequestHeader).tryRead(0xc4264f9b00, 0xc421235020, 0x1, 0x4539d0, 0xc42014f400)
        /go/src/github.com/valyala/fasthttp/header.go:1331 +0x5e
github.com/valyala/fasthttp.(*RequestHeader).Read(0xc4264f9b00, 0xc421235020, 0xc42008c4b8, 0x0)
        /go/src/github.com/valyala/fasthttp/header.go:1317 +0x56
github.com/valyala/fasthttp.(*Request).readLimitBody(0xc4264f9b00, 0xc421235020, 0x400000, 0x0, 0xd, 0xc420345e70)
        /go/src/github.com/valyala/fasthttp/http.go:876 +0x3b
github.com/valyala/fasthttp.(*Server).serveConn(0xc42008c3c0, 0x870b80, 0xc420b74a80, 0x6fda01, 0xc421b20101)
        /go/src/github.com/valyala/fasthttp/server.go:1509 +0x15aa
github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0x870b80, 0xc420b74a80, 0x1, 0x0)
        /go/src/github.com/valyala/fasthttp/server.go:1280 +0x3e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc42010e480, 0xc427ef0400)
        /go/src/github.com/valyala/fasthttp/workerpool.go:210 +0xdc
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc42010e480, 0xc427ef0400, 0x68a0e0, 0xc427ef0400)
        /go/src/github.com/valyala/fasthttp/workerpool.go:182 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /go/src/github.com/valyala/fasthttp/workerpool.go:181 +0x13c

goroutine 73463 [IO wait]:
internal/poll.runtime_pollWait(0x7fd9b948ef80, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc421c5fd18, 0x72, 0xffffffffffffff00, 0x86c800, 0x869458)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc421c5fd18, 0xc42567d000, 0x400, 0x400)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc421c5fd00, 0xc42567d000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc421c5fd00, 0xc42567d000, 0x400, 0x400, 0x5dad7dc3bb02c255, 0x28a373c8b2becba3, 0x5dad7dc3bb02c255)
        /usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e580, 0xc42567d000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc4202f3080, 0x7fd9b9483128, 0xc42000e580, 0x5, 0xc42000e580, 0x43437b)
        /usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc4224a0a80, 0x71cd17, 0xc4224a0ba0, 0xc42001e070)
        /usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc4224a0a80, 0xc42108a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).fill(0xc426847260)
        /usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc426847260, 0x1, 0xc423594900, 0x7fd9b9483100, 0xc424759cb0, 0x6586db, 0x6b2de0)
        /usr/local/go/src/bufio/bufio.go:129 +0x3a
github.com/valyala/fasthttp.(*RequestHeader).tryRead(0xc4218b6d80, 0xc426847260, 0x1, 0xc4224a0a80, 0xc422f0b000)
        /go/src/github.com/valyala/fasthttp/header.go:1331 +0x5e
github.com/valyala/fasthttp.(*RequestHeader).Read(0xc4218b6d80, 0xc426847260, 0xc42008c4b8, 0x0)
        /go/src/github.com/valyala/fasthttp/header.go:1317 +0x56
github.com/valyala/fasthttp.(*Request).readLimitBody(0xc4218b6d80, 0xc426847260, 0x400000, 0x0, 0xed23c7cff, 0x8a2fa0)
        /go/src/github.com/valyala/fasthttp/http.go:876 +0x3b
github.com/valyala/fasthttp.(*Server).serveConn(0xc42008c3c0, 0x870b80, 0xc4224a0a80, 0x6fda01, 0xc426950101)
        /go/src/github.com/valyala/fasthttp/server.go:1509 +0x15aa
github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0x870b80, 0xc4224a0a80, 0x1, 0x0)
        /go/src/github.com/valyala/fasthttp/server.go:1280 +0x3e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc42010e480, 0xc42934da00)
        /go/src/github.com/valyala/fasthttp/workerpool.go:210 +0xdc
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc42010e480, 0xc42934da00, 0x68a0e0, 0xc42934da00)
        /go/src/github.com/valyala/fasthttp/workerpool.go:182 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /go/src/github.com/valyala/fasthttp/workerpool.go:181 +0x13c

goroutine 73102 [IO wait]:
internal/poll.runtime_pollWait(0x7fd9b94f1880, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc426ef2518, 0x72, 0xffffffffffffff00, 0x86c800, 0x869458)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc426ef2518, 0xc422048000, 0x400, 0x400)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc426ef2500, 0xc422048000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc426ef2500, 0xc422048000, 0x400, 0x400, 0x10, 0x0, 0xc426ef2518)
        /usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420582f58, 0xc422048000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc422dbcde0, 0x7fd9b9483128, 0xc420582f58, 0x5, 0xc420582f58, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc4203c1c00, 0x71cd17, 0xc4203c1d20, 0xc42008c4e8)
        /usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc4203c1c00, 0xc425932ed8, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1134 +0x110
github.com/valyala/fasthttp.acquireByteReader(0xc424cd1de0, 0x870b80, 0xc4203c1c00, 0x7fd9b94830d8)
        /go/src/github.com/valyala/fasthttp/server.go:1808 +0x143
github.com/valyala/fasthttp.(*Server).serveConn(0xc42008c3c0, 0x870b80, 0xc4203c1c00, 0x6fda01, 0xc420130101)
        /go/src/github.com/valyala/fasthttp/server.go:1500 +0x1699
github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0x870b80, 0xc4203c1c00, 0x1, 0x0)
        /go/src/github.com/valyala/fasthttp/server.go:1280 +0x3e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc42010e480, 0xc4208c0920)
        /go/src/github.com/valyala/fasthttp/workerpool.go:210 +0xdc
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc42010e480, 0xc4208c0920, 0x68a0e0, 0xc4208c0920)
        /go/src/github.com/valyala/fasthttp/workerpool.go:182 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /go/src/github.com/valyala/fasthttp/workerpool.go:181 +0x13c

```

And same stack is thrown for 1000s of routines. It does look like it's trying to read unavailable data, but my request handler doesn't touch ctx. Would much appreciate, if somebody could enlighten me a bit with this. Thanks

**Comment by erikdubbelboer** [comment]
Yes. Requests are handled in different goroutines so you have multiple concurrent writes to `chunk`. You need to protect it with a `sync.Mutex` for example.

**Comment by mr-moon** [comment]
Thank you.
