### ISSUE TITLE
Getting this error from fasthttp

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#617]
I'm using the reverse proxy here https://github.com/valyala/fasthttp/issues/64#issuecomment-194880575
and wrote a web accelerator 
https://pastebin.com/xhvEQsRU
my goroutine is crashing.
How do I resolve this?
```

panic: runtime error: index out of range

goroutine 8607 [running]:
github.com/valyala/fasthttp.(*ResponseHeader).AppendBytes(0xc0001da7a8, 0xc00026c800, 0x0, 0x400, 0xa, 0x10, 0xbdbce0)
        /go/src/github.com/valyala/fasthttp/header.go:1510 +0x1bc4
github.com/valyala/fasthttp.(*ResponseHeader).Header(0xc0001da7a8, 0xa, 0x10, 0x0)
        /go/src/github.com/valyala/fasthttp/header.go:1474 +0x50
github.com/valyala/fasthttp.(*ResponseHeader).Write(0xc0001da7a8, 0xc000062740, 0x853be0, 0xc0005e3301)
        /go/src/github.com/valyala/fasthttp/header.go:1458 +0x2b
github.com/valyala/fasthttp.(*Response).Write(0xc0001da7a8, 0xc000062740, 0x1000, 0x1000)
        /go/src/github.com/valyala/fasthttp/http.go:1401 +0xab
github.com/valyala/fasthttp.writeResponse(0xc0001da500, 0xc000062740, 0xa, 0xa)
        /go/src/github.com/valyala/fasthttp/server.go:2221 +0x4e
github.com/valyala/fasthttp.(*Server).serveConn(0xc000200000, 0x90c080, 0xc00020c118, 0x0, 0x0)
        /go/src/github.com/valyala/fasthttp/server.go:2068 +0x767
github.com/valyala/fasthttp.(*Server).serveConn-fm(0x90c080, 0xc00020c118, 0x1, 0x0)
        /go/src/github.com/valyala/fasthttp/server.go:1578 +0x3e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000210000, 0xc00016c760)
        /go/src/github.com/valyala/fasthttp/workerpool.go:212 +0xc3
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc000210000, 0xc00016c760, 0x7e35a0, 0xc00016c760)
        /go/src/github.com/valyala/fasthttp/workerpool.go:184 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /go/src/github.com/valyala/fasthttp/workerpool.go:183 +0x119
```

**Comment by hiqsociety** [comment]
i think i didnt do resp.Reset()
trying now and will revert.

**Comment by hiqsociety** [comment]
i did resp.Reset() but still crashed with same error.

above line 17
                                         resp.Reset()
                                         if err := proxyClient.Do(req, resp); err != nil {


how do i resolve this?

**Comment by hiqsociety** [comment]
resolved with
                                 reqTemp := fasthttp.AcquireRequest()
                                respTemp := fasthttp.AcquireResponse()
