### ISSUE TITLE
Benchmark panics

### ISSUE THREAD

**Issue by jhinrichsen** [valyala/fasthttp#742]
When trying to run the command on a Macbook Pro using Go 1.13.7:

````
% GOMAXPROCS=1 go test -trimpath -bench=NetHTTPServerGet -benchmem -benchtime=10s
panic: EOF

goroutine 6496 [running]:
github.com/valyala/fasthttp.benchmarkServer.func1(0x15654c0, 0xc00075e1c0, 0xc000768000, 0xc0001bb2c0)
	github.com/valyala/fasthttp@/server_timing_test.go:451 +0x8c
created by github.com/valyala/fasthttp.benchmarkServer
	github.com/valyala/fasthttp@/server_timing_test.go:449 +0xe9
exit status 2
FAIL	github.com/valyala/fasthttp	47.491s
````

**Comment by erikdubbelboer** [comment]
Thanks for reporting. The benchmark was indeed broken and should be fixed now.
