### ISSUE TITLE
Calling ListenAndServeTLS multiple times on a Server，fatal error: concurrent map writes

### ISSUE THREAD

**Issue by wenjy** [valyala/fasthttp#959]
err:
```
fatal error: concurrent map writes

goroutine 32 [running]:
runtime.throw(0x705e69, 0x15)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0002abda0 sp=0xc0002abd70 pc=0x436a72
runtime.mapassign_faststr(0x6bcaa0, 0xc0001fe090, 0xc0002be070, 0xd, 0xc00007a7d8)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc0002abe08 sp=0xc0002abda0 pc=0x4155b1
crypto/tls.(*Config).BuildNameToCertificate(0xc000001500)
	/usr/local/go/src/crypto/tls/common.go:1248 +0x1a5 fp=0xc0002abe78 sp=0xc0002abe08 pc=0x5ace85
github.com/valyala/fasthttp.(*Server).ServeTLS(0xc0000d0240, 0x75e500, 0xc00029f3c0, 0xc000146f00, 0x2d, 0xc000146f30, 0x2d, 0x0, 0x2)
	/home/www/go/pkg/mod/github.com/valyala/fasthttp@v1.19.0/server.go:1579 +0xb8 fp=0xc0002abed8 sp=0xc0002abe78 pc=0x682d18
github.com/valyala/fasthttp.(*Server).ListenAndServeTLS(0xc0000d0240, 0xc0000180e0, 0x6, 0xc000146f00, 0x2d, 0xc000146f30, 0x2d, 0x0, 0x0)
	/home/www/go/pkg/mod/github.com/valyala/fasthttp@v1.19.0/server.go:1527 +0x126 fp=0xc0002abf48 sp=0xc0002abed8 pc=0x682ba6
main.main.func2(0xc0000d0240, 0xc000146f00, 0x2d, 0xc000146f30, 0x2d, 0x271d)
	fasthttp_tls_server_err.go:31 +0xc5 fp=0xc0002abfb0 sp=0xc0002abf48 pc=0x68ffa5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0002abfb8 sp=0xc0002abfb0 pc=0x46a3a1
created by main.main
	fasthttp_tls_server_err.go:30 +0x1ae

goroutine 1 [runnable]:
main.main()
	fasthttp_tls_server_err.go:29 +0x1ca
```

example code

```
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"

	"github.com/valyala/fasthttp"
)

var AppPath string

func main() {
	var err error
	if AppPath, err = filepath.Abs(filepath.Dir(os.Args[0])); err != nil {
		panic(err)
	}

	server := &fasthttp.Server{
		Handler: func(ctx *fasthttp.RequestCtx) {

		},
	}

	certFile := AppPath + "/ssl/test.crt"
	keyFile := AppPath + "/ssl/test.key"

	for port := 10000; port <= 10020; port++ {
		go func(port int) {
			err := server.ListenAndServeTLS(":"+strconv.Itoa(port), certFile, keyFile)
			if err != nil {
				fmt.Println(err)
			}
		}(port)
	}

	for {

	}

}
```

**Comment by erikdubbelboer** [comment]
I'm not sure if the way you are using this is something we should fix. Each time you call `ListenAndServeTLS` with the cert and key as argument we don't know if its a new certificate or not. So currently it would each time add the certificate to the TLS config and build the state. If you add the same certificate lots of times that might be overkill.

What you could do here is call `server.AppendCert(certFile, keyFile)` once and pass `nil, nil` to `ListenAndServeTLS`.

But that doesn't take away that fact that we internally call `BuildNameToCertificate` multiple times concurrently which is not safe. I'll see if I can make a pull request this week.

If you need a fix right now you can also build the TLS listeners yourself ([see this example](https://github.com/valyala/fasthttp/issues/487#issuecomment-446974452)) and pass that to `server.Serve(ln)`.

**Comment by wenjy** [comment]
Thanks~

**Comment by erikdubbelboer** [comment]
This has been fixed in https://github.com/valyala/fasthttp/commit/838d3abc3db643ec3cf4352c067bf8cde515886d I'll tag a release on Monday.
